export const SITE_METADATA = {
  title: "Burak's Tech Insights: AI, Software, and More",
  author: "Burak Ince",
  jobTitle: "Lead Software Developer",
  worksFor: "Thoughtworks",
  description:
    "Discover the latest in technology, software development, and AI trends with Burak's in-depth analysis and expert insights.",
  siteUrl: "https://www.burakince.com",
  siteRepo: "https://github.com/burakince/burakince.github.io",
  email: "me@burakince.com",
  github: "https://github.com/burakince",
  twitter: "https://twitter.com/burakinc",
  keybase: "https://keybase.io/burakince",
  huggingface: "https://huggingface.co/burakince",
  linkedin: "https://www.linkedin.com/in/inceburak/",
  keywords: [
    "latest tech trends",
    "technology updates",
    "emerging technologies",
    "software engineering",
    "programming languages",
    "coding best practices",
    "AI developments",
    "machine learning",
    "deep learning",
    "cybersecurity tips",
    "data protection",
    "security threats",
    "latest gadgets",
    "tech reviews",
    "device comparisons",
    "tech industry updates",
    "technology news",
    "tech market trends",
    "tech tutorials",
    "coding tutorials",
    "software guides",
    "product reviews",
    "technology product reviews",
    "tech gadgets reviews",
    "cloud technology",
    "cloud services",
    "cloud solutions",
    "tech innovation",
    "tech breakthroughs",
    "innovative tech ideas",
  ],
  analytics: {
    googleAnalytics: {
      googleAnalyticsId: "G-37SPDQK30W", // e.g. G-XXXXXXX
    },
  },
};
